In [1]:
from rasterio.plot import show
from rasterio.merge import merge
import rasterio as rio
from rasterio import features
import rioxarray

from pathlib import Path
import glob
import xarray as xr
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import geopandas as gpd


In [2]:
def make_radolan_xarray(path, str_start, str_end, mini, maxi):
    #path = 'C:/Uni Jena/GEO 411/Data/Radolan/Thueringen/'
    #getall file paths from path
    file_list = glob.glob(path + "raa01*.tif")

    # make empty list
    array_list = []
    
    for i in file_list[mini:maxi]:
        #open ds from filepath
        #da = xr.open_rasterio(i)
        da = rioxarray.open_rasterio(i)
        #convert date string from filename to timestamp
        time = pd.to_datetime(i[str_start:str_end], format='%y%m%d%H%M')
        # assign timestamp value to variable time
        da = da.assign_coords({"time": (time)})
        #da = da.expand_dims(dim="time")
        #delete default variable band
        #da = da.drop_vars("band")
        #put array in list
        array_list.append(da)

    #concatenate arrays from list to one xarray    
    radolan_xr = xr.concat([array_list[x] for x in range(len(array_list))], dim = "time")
    return radolan_xr

In [3]:
radolan_thueringen = make_radolan_xarray('C:/Uni Jena/GEO 411/Data/Radolan/Thueringen/', 59,69,0,43786)

In [4]:
file_list = glob.glob('C:/Uni Jena/GEO 411/Data/Radolan/Thueringen/' + "raa01*.tif")
radolan_thueringen1 = make_radolan_xarray('C:/Uni Jena/GEO 411/Data/Radolan/Thueringen/', 59,69,43787,len(file_list))

In [5]:
radolan_thueringen1

<xarray.DataArray (time: 3118, band: 1, y: 59, x: 53)>
array([[[[-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999,     0,     0, ..., -9999, -9999, -9999],
         ...,
         [-9999, -9999, -9999, ...,     0,     0, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999]]],


       [[[-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999,     0,     0, ..., -9999, -9999, -9999],
         ...,
         [-9999, -9999, -9999, ...,     0,     0, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999]]],


       [[[-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
...
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999]]],


       [[[-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999,   380,   370, ..., -9999, -9999, -9999],
         ...,
         [-9999, -9999, -9999, ...,   630,   570, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999]]],


       [[[-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999,   380,   360, ..., -9999, -9999, -9999],
         ...,
         [-9999, -9999, -9999, ...,   590,   550, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999],
         [-9999, -9999, -9999, ..., -9999, -9999, -9999]]]], dtype=int16)
Coordinates:
  * band         (band) int32 1
  * x            (x) float64 6.56e+05 6.569e+05 ... 7.046e+05 7.056e+05
  * y            (y) float64 5.673e+06 5.672e+06 ... 5.618e+06 5.617e+06
    spatial_ref  int32 0
  * time         (time) datetime64[ns] 2023-01-01T00:50:00 ... 2023-05-11T06:...
Attributes:
    AREA_OR_POINT:             Area
    STATISTICS_MAXIMUM:        0
    STATISTICS_MEAN:           0
    STATISTICS_MINIMUM:        0
    STATISTICS_STDDEV:         0
    STATISTICS_VALID_PERCENT:  85.67
    _FillValue:                -9999
    scale_factor:              1.0
    add_offset:                0.0

In [6]:
'''
file_list = glob.glob('C:/Uni Jena/GEO 411/Data/Radolan/Thueringen/' + "raa01*.tif")
#file_list['2305110650']
#list = ["hello, whats up?", "my name is...", "goodbye"]
for index, string in enumerate(file_list):
     if '2305110650' in string:
             print (index)
             
 '''

'\nfile_list = glob.glob(\'C:/Uni Jena/GEO 411/Data/Radolan/Thueringen/\' + "raa01*.tif")\n#file_list[\'2305110650\']\n#list = ["hello, whats up?", "my name is...", "goodbye"]\nfor index, string in enumerate(file_list):\n     if \'2305110650\' in string:\n             print (index)\n             \n '

In [7]:
radolan_thueringen = radolan_thueringen.rio.write_crs('epsg:25832', inplace=True)

In [8]:
radolan_thueringen1 = radolan_thueringen1.rio.write_crs('epsg:25832', inplace=True)

In [9]:
#radolan_unterfranken = make_radolan_xarray('C:/Uni Jena/GEO 411/Data/Radolan/Unterfranken/',61,71)
#radolan_unterfranken = radolan_unterfranken.rio.set_crs('epsg:25832')
#radolan_unterfranken = radolan_unterfranken.where(radolan_unterfranken != -9999.)

In [10]:
print(radolan_thueringen.rio.crs)

PROJCS["ETRS89 / UTM zone 32N",GEOGCS["ETRS89",DATUM["European_Terrestrial_Reference_System_1989",SPHEROID["GRS 1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4258"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","25832"]]


In [11]:
radolan_thueringen = radolan_thueringen/100


NameError: name 'radolan_thueringen0' is not defined

In [14]:
radolan_thueringen = (radolan_thueringen.where(radolan_thueringen != -99.99))

In [15]:
radolan_thueringen

<xarray.DataArray (time: 43786, band: 1, y: 59, x: 53)>
array([[[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, 0.7, 0.7, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., 1.9, 1.8, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, 0.7, 0.7, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., 1.9, 1.8, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
...
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, 0. , 0. , ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., 0. , 0. , nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, 0. , 0. , ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., 0. , 0. , nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]]])
Coordinates:
  * band         (band) int32 1
  * x            (x) float64 6.56e+05 6.569e+05 ... 7.046e+05 7.056e+05
  * y            (y) float64 5.673e+06 5.672e+06 ... 5.618e+06 5.617e+06
  * time         (time) datetime64[ns] 2018-01-01T00:50:00 ... 2022-12-31T22:...
    spatial_ref  int32 0

In [ ]:
radolan_thueringen1 = radolan_thueringen1/100

In [18]:
radolan_thueringen1 = (radolan_thueringen1.where(radolan_thueringen1 != -99.99))

In [19]:
radolan_thueringen1

<xarray.DataArray (time: 3118, band: 1, y: 59, x: 53)>
array([[[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, 0. , 0. , ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., 0. , 0. , nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, 0. , 0. , ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., 0. , 0. , nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
...
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, 3.8, 3.7, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., 6.3, 5.7, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]],


       [[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, 3.8, 3.6, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., 5.9, 5.5, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]]])
Coordinates:
  * band         (band) int32 1
  * x            (x) float64 6.56e+05 6.569e+05 ... 7.046e+05 7.056e+05
  * y            (y) float64 5.673e+06 5.672e+06 ... 5.618e+06 5.617e+06
  * time         (time) datetime64[ns] 2023-01-01T00:50:00 ... 2023-05-11T06:...
    spatial_ref  int32 0

In [20]:
geodf = gpd.read_file(r'C:\Uni Jena\GEO 411\Data\Feldgrenzen\thueringen_stauenaesse_bekannt.shp')

PROJ: proj_create_from_database: Cannot find proj.db


In [21]:
#get geometries of waterlogged fields
geodf = geodf[geodf['cat']=='staunaesse']
geodf = geodf.set_crs('epsg:25832', allow_override=True)
stau0 = geodf[geodf['field_id']==0].geometry
stau1 = geodf[geodf['field_id']==1].geometry
stau2 = geodf[geodf['field_id']==2].geometry
stau3 = geodf[geodf['field_id']==3].geometry
stau4 = geodf[geodf['field_id']==4].geometry
stau5 = geodf[geodf['field_id']==5].geometry
stau6 = geodf[geodf['field_id']==6].geometry

In [22]:
#clipped0 = radolan_thueringen.rio.write_crs('epsg:25832').clip(stau0, all_touched=True)

In [23]:
clipped0 = radolan_thueringen.rio.clip(stau0, all_touched=True)
clipped0 = clipped0.where(clipped0 != -9999.)
clipped1 = radolan_thueringen.rio.clip(stau1, all_touched=True)
clipped1 = clipped1.where(clipped1 != -9999.)
clipped2 = radolan_thueringen.rio.clip(stau2, all_touched=True)
clipped2 = clipped2.where(clipped2 != -9999.)
clipped3 = radolan_thueringen.rio.clip(stau3, all_touched=True)
clipped3 = clipped3.where(clipped3 != -9999.)
clipped4 = radolan_thueringen.rio.clip(stau4, all_touched=True)
clipped4 = clipped4.where(clipped4 != -9999.)
clipped5 = radolan_thueringen.rio.clip(stau5, all_touched=True)
clipped5 = clipped5.where(clipped5 != -9999.)
clipped6 = radolan_thueringen.rio.clip(stau6, all_touched=True)
clipped6 = clipped6.where(clipped6 != -9999.)



In [24]:
clipped5

<xarray.DataArray (time: 43786, band: 1, y: 1, x: 1)>
array([[[[1.]]],


       [[[1.]]],


       [[[1.]]],


       ...,


       [[[0.]]],


       [[[0.]]],


       [[[0.]]]])
Coordinates:
  * band         (band) int32 1
  * x            (x) float64 6.722e+05
  * y            (y) float64 5.623e+06
  * time         (time) datetime64[ns] 2018-01-01T00:50:00 ... 2022-12-31T22:...
    spatial_ref  int32 0

In [25]:
clipped00 = radolan_thueringen1.rio.clip(stau0, all_touched=True)
clipped00 = clipped00.where(clipped00 != -9999)
clipped11 = radolan_thueringen1.rio.clip(stau1, all_touched=True)
clipped11 = clipped11.where(clipped11 != -9999)
clipped22 = radolan_thueringen1.rio.clip(stau2, all_touched=True)
clipped22 = clipped22.where(clipped22 != -9999)
clipped33 = radolan_thueringen1.rio.clip(stau3, all_touched=True)
clipped33 = clipped33.where(clipped33 != -9999)
clipped44 = radolan_thueringen1.rio.clip(stau4, all_touched=True)
clipped44 = clipped44.where(clipped44 != -9999)
clipped55 = radolan_thueringen1.rio.clip(stau5, all_touched=True)
clipped55 = clipped55.where(clipped55 != -9999)
clipped66 = radolan_thueringen1.rio.clip(stau6, all_touched=True)
clipped66 = clipped66.where(clipped66 != -9999)


In [27]:
clipped0 = xr.concat([clipped0, clipped00], dim='time')
clipped1 = xr.concat([clipped1, clipped11], dim='time')
clipped2 = xr.concat([clipped2, clipped22], dim='time')
clipped3 = xr.concat([clipped3, clipped33], dim='time')
clipped4 = xr.concat([clipped4, clipped44], dim='time')
clipped5 = xr.concat([clipped5, clipped55], dim='time')
clipped6 = xr.concat([clipped6, clipped66], dim='time')

In [28]:
radolan_thueringen_new = xr.concat([radolan_thueringen, radolan_thueringen1], dim='time')

In [ ]:
#radolan_thueringen_new
#radolan_thueringen_new = (radolan_thueringen_new.where(radolan_thueringen_new != -9999))


In [ ]:

'''
rad_thuer_sub = radolan_thueringen.where((radolan_thueringen.x > 657890.388099) & 
                         (radolan_thueringen.x < 659797.546272) & 
                         (radolan_thueringen.y > 5668932.436683) & 
                         (radolan_thueringen.y < 5670839.594857), drop=True)
                         
'''

In [31]:
clip0_list = []
clip1_list = []
clip2_list = []
clip3_list = []
clip4_list = []
clip5_list = []
clip6_list = []
average = []

#get timestamps
time_list_thuer = list(clipped0.time.values)

#for each dataset get mean values for each scene
for i in range(len(clipped0)):
    a0 = float(clipped0[i].mean())
    a1 = float(clipped1[i].mean())
    a2 = float(clipped2[i].mean())
    a3 = float(clipped3[i].mean())
    a4 = float(clipped4[i].mean())
    a5 = float(clipped5[i].mean())
    a6 = float(clipped6[i].mean())
    a = float(radolan_thueringen_new[i].mean())
    
    clip0_list.append(a0)
    clip1_list.append(a1)
    clip2_list.append(a2)
    clip3_list.append(a3)
    clip4_list.append(a4)
    clip5_list.append(a5)
    clip6_list.append(a6)
    average.append(a)

In [32]:
df = pd.DataFrame()
df['date'] = time_list_thuer
df['prec0'] = clip0_list
df['prec1'] = clip1_list
df['prec2'] = clip2_list
df['prec3'] = clip3_list
df['prec4'] = clip4_list
df['prec5'] = clip5_list
df['prec6'] = clip6_list
df['prec_average'] = average
df.index=df['date']
del df['date']
df_2018 = df[(df.index>='2018-01-01 00:00:00') & (df.index<='2018-12-31 23:59:59')]

In [33]:
df.to_csv(r'C:\Uni Jena\GEO 411\plots\data.csv', sep=';', decimal=',')

In [2]:
df

NameError: name 'df' is not defined